// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery"], function($) {
    var App;
    return App = (function() {
      function App() {
        console.log('App running...');
        this._addListeners();
      }

      App.prototype._addListeners = function() {};

      return App;

    })();
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
