source:      .
destination: ./_site
exclude:     [coffee, README.md, TODO.md, Gemfile, Gemfile.lock]
pygments:    true
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
encoding:    UTF-8