source:      .
destination: ./_site
exclude:     [coffee, myth, README.md, TODO.md, Gemfile, Gemfile.lock, package.json, node_modules, gulpfile.js]
highlighter: pygments
host:        0.0.0.0
port:        3000
baseurl:     /
url:         http://localhost:3000
encoding:    UTF-8
permalink:   date
markdown:    kramdown
gems:
- jekyll-sitemap
- jemoji
- jekyll-redirect-from